version: '3.8'
services:
  node-service:
    container_name: node-service
    build: ./docker/node-env
    volumes:
      - ./docker/node-env:/app
    networks:
      - code-network
    ports:
      - "3000:3000"

networks:
  code-network:
    driver: bridge
